/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heroku.java;

import org.json.JSONObject;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HueAPI {
    
    @RequestMapping(value = "/hue", produces = "application/json")
    String index() {
        final JSONObject jsObj = new JSONObject();
        jsObj.put("Hello", "Hue");
        
        return jsObj.toString();
    }
}